---
title: "ABS Census -- Rescale Indices"
author: "Nicholas S Spyrison"
date: "September 2018"  #"`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  eval = FALSE,
  echo = TRUE,
  comment = "",
  fig.height = 3,
  fig.width = 7,
  fig.align = "center",
  cache = FALSE
)
```

## The functions

```{r cars}
ABS_filt <- function(x) {
  n_na_s <- sum(is.na(x) )
  nrow_s <- nrow(x)
  x <- x[(x[,  1] != "Total"), ]  # CD/SA1
  x[(!is.na(x[,  2]) & x[,  2] <=   9),  2] <- NA # Population
  x[(!is.na(x[,  3]) & x[,  3] <= .01),  3] <- NA # Ethnicity-raw-count
  x[(!is.na(x[,  4]) & x[,  4] <= .01),  4] <- NA # Ethnicity-index
  x[(!is.na(x[,  5]) & x[,  5] <= .01),  5] <- NA # Ethnicity-raw-normalized
  x[(!is.na(x[,  6]) & x[,  6] <= .01),  6] <- NA # Ethnicity-norm-index
  x[(!is.na(x[,  7]) & x[,  7] <= .01),  7] <- NA # Mobility-raw-pct
  x[(!is.na(x[,  8]) & x[,  8] <= .01),  8] <- NA # Mobility-index
  x[(!is.na(x[,  9]) & x[,  9] <= .01),  9] <- NA # Generation-raw-SI
  x[(!is.na(x[, 10]) & x[, 10] <= .01), 10] <- NA # Generation-index
  x[(!is.na(x[, 11]) & x[, 11] <= .01), 11] <- NA # Income-raw-SI
  x[(!is.na(x[, 12]) & x[, 12] <= .01), 12] <- NA # Income-index
  x[(!is.na(x[, 13]) & x[, 13] <= .01), 13] <- NA # Education-raw-SI
  x[(!is.na(x[, 14]) & x[, 14] <= .01), 14] <- NA # Education-index
  print(paste0("Droped `total` rows: ", nrow_s - nrow(x)))
  print(paste0("Number of NAs intorduces: ", sum(is.na(x) ) - n_na_s ) )
  print(paste0("NAs start:", n_na_s, ", NAs end: ",   sum(is.na(x) ) ) )
  return(x)
}

ABS_as_numeric <- function(df) {
  ans <- apply(df, 2, as.numeric)
  return(ans)
}

ABS_rescale01 <- function(df) {
  ans <- apply(df, 2, function(x) {(x - min(x)) / diff(range(x))} )
  return(ans)
}
```

## Read indices files

```{r}
#library("readxl")
### Sydney '06, '11, '16 *.xlsx not produced by Nick as of 25/09/2018.
readxl::read_xlsx(
  "./data/SMA-2006-2016-DA-diversityindices.xlsx", na = c("NA", "", "NULL"),
  sheet = "2006", n_max = 123456, guess_max = 7000, skip = 1) %>%
  tibble::as_tibble() -> sydn06
readxl::read_xlsx(
  "./data/SMA-2006-2016-DA-diversityindices.xlsx", na = c("NA", "", "NULL"),
  sheet = "2011", n_max = 123456, guess_max = 9999, skip = 1) %>%
  tibble::as_tibble() -> sydn11
readxl::read_xlsx(
  "./data/SMA-2006-2016-DA-diversityindices.xlsx", na = c("NA", "", "NULL"),
  sheet = "2016", n_max = 123456, guess_max = 9999, skip = 1) %>%
  tibble::as_tibble() -> sydn16

#library("readr")
### Sydney '01, Melbourne '01, '06, '11, '16 *.csv's were produced by Nick.
readr::read_csv("./output/Sydney_2001_diversityindices.csv",
         n_max = 123456, guess_max = 7000, na = c("NA", "", "NULL") ) %>%
  tibble::as_tibble() -> sydn01
readr::read_csv("./output/Melbourne_2001_diversityindices.csv",
         n_max = 123456, guess_max = 7000, na = c("NA", "", "NULL") ) %>%
  tibble::as_tibble() -> melb01
readr::read_csv("./output/Melbourne_2006_diversityindices.csv",
         n_max = 123456, guess_max = 7000, na = c("NA", "", "NULL") ) %>%
  tibble::as_tibble() -> melb06
readr::read_csv("./output/Melbourne_2011_diversityindices.csv",
         n_max = 123456, guess_max = 9999, na = c("NA", "", "NULL") ) %>%
  tibble::as_tibble() -> melb11
readr::read_csv("./output/Melbourne_2016_diversityindices.csv",
         n_max = 123456, guess_max = 9999, na = c("NA", "", "NULL") ) %>%
  tibble::as_tibble() -> melb16
```

## Manipulate indicies files

```{r}
### Remove "Total" row, handle near 0's.
sydn01 <- ABS_filt(sydn01) # 1 dropped.
sydn06 <- ABS_filt(sydn06) # 1 dropped.
sydn11 <- ABS_filt(sydn11) # 0 dropped.
sydn16 <- ABS_filt(sydn16) # 0 dropped.
melb01 <- ABS_filt(melb01) # 0 dropped.
melb06 <- ABS_filt(melb06) # 1 dropped. 0 dropped after last change.
melb11 <- ABS_filt(melb11) # 1 dropped. 0 dropped after last change.
melb16 <- ABS_filt(melb16) # 0 dropped.

### Handle data type 
sydn01[, c(3:14)] <- ABS_as_numeric(sydn01[, c(3:14)])
sydn06[, c(3:14)] <- ABS_as_numeric(sydn06[, c(3:14)])
sydn11[, c(3:14)] <- ABS_as_numeric(sydn11[, c(3:14)])
sydn16[, c(3:14)] <- ABS_as_numeric(sydn16[, c(3:14)])
melb01[, c(3:14)] <- ABS_as_numeric(melb01[, c(3:14)])
melb06[, c(3:14)] <- ABS_as_numeric(melb06[, c(3:14)])
melb11[, c(3:14)] <- ABS_as_numeric(melb11[, c(3:14)])
melb16[, c(3:14)] <- ABS_as_numeric(melb16[, c(3:14)])

### Rescale01
# TODO: fix issue indutroducting near all NAs.
sydn01[, c(3,5,7,9,11,13)] <- ABS_rescale01(sydn01[, c(3,5,7,9,11,13)])
sydn06[, c(3,5,7,9,11,13)] <- ABS_rescale01(sydn06[, c(3,5,7,9,11,13)])
sydn11[, c(3,5,7,9,11,13)] <- ABS_rescale01(sydn11[, c(3,5,7,9,11,13)])
sydn16[, c(3,5,7,9,11,13)] <- ABS_rescale01(sydn16[, c(3,5,7,9,11,13)])
melb01[, c(3,5,7,9,11,13)] <- ABS_rescale01(melb01[, c(3,5,7,9,11,13)])
melb06[, c(3,5,7,9,11,13)] <- ABS_rescale01(melb06[, c(3,5,7,9,11,13)])
melb11[, c(3,5,7,9,11,13)] <- ABS_rescale01(melb11[, c(3,5,7,9,11,13)])
melb16[, c(3,5,7,9,11,13)] <- ABS_rescale01(melb16[, c(3,5,7,9,11,13)])
```

## Wrtie output files

```{r}
write.csv(x = sydn01, row.names = FALSE,
          file = "./output/Sydney_2001_diversityindices.csv")
write.csv(x = sydn06, row.names = FALSE,
          file = "./output/Sydney_2006_diversityindices.csv")
write.csv(x = sydn11, row.names = FALSE,
          file = "./output/Sydney_2011_diversityindices.csv")
write.csv(x = sydn16, row.names = FALSE,
          file = "./output/Sydney_2016_diversityindices.csv")
write.csv(x = melb01, row.names = FALSE,
          file = "./output/Melbourne_2001_diversityindices.csv")
write.csv(x = melb06, row.names = FALSE,
          file = "./output/Melbourne_2006_diversityindices.csv")
write.csv(x = melb11, row.names = FALSE,
          file = "./output/Melbourne_2011_diversityindices.csv")
write.csv(x = melb16, row.names = FALSE,
          file = "./output/Melbourne_2016_diversityindices.csv")
```

```{r, echo=FALSE}
##### Manual Check
## library("GGally")
# GGally::ggpairs(sydn06[, 2:6])
# GGally::ggpairs(sydn06[, 7:14])
# # Do SI values stay within [0,1]?
```
